# Generated by Django 6.0.3 on 2026-04-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telegram User username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram User first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram User last name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telegram User phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='bot_user_is_acti_9e1a71_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100, verbose_name='Full name')),
                ('phone', models.CharField(db_index=True, max_length=100, verbose_name='Telegram User phone number')),
                ('course_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Course Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'full_name', 'phone', 'course'], name='bot_registe_user_id_c9216a_idx')],
            },
        ),
    ]
