# Generated by Django 6.0.3 on 2026-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telegram User username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram User first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram User last name')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Telegram User phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='bot_user_is_acti_9e1a71_idx')],
            },
        ),
    ]
