# Generated by Django 6.0.3 on 2026-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='phone',
            field=models.CharField(db_index=True, default=0, max_length=100, verbose_name='Telegram User phone number'),
            preserve_default=False,
        ),
    ]
