# Generated by Django 6.0.3 on 2026-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_registereduser_phone'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registereduser',
            name='bot_registe_user_id_2525e5_idx',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='full_name',
            field=models.CharField(db_index=True, default=0, max_length=100, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='registereduser',
            index=models.Index(fields=['user', 'full_name', 'phone', 'course'], name='bot_registe_user_id_c9216a_idx'),
        ),
    ]
