# Generated by Django 6.0.3 on 2026-03-27 14:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Course Name')),
                ('description', models.TextField(db_index=True, verbose_name='Course Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('photo', models.ImageField(upload_to='course_images/', verbose_name='Course Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'description'], name='course_cour_name_2a6acf_idx')],
            },
        ),
    ]
