# Generated by Django 6.0.3 on 2026-04-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0002_alter_certificate_mentor'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
