# Generated by Django 6.0.3 on 2026-04-06 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='teammate_images/', verbose_name='Photo')),
                ('full_name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Full Name')),
                ('about', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='About')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Github Link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='', verbose_name='Presentation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammate.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50, verbose_name='Recipient')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificate')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammate.teammate', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teammate',
            index=models.Index(fields=['full_name'], name='teammate_te_full_na_efa8ca_idx'),
        ),
    ]
