# Generated by Django 6.0.3 on 2026-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50, verbose_name='Recipient')),
                ('mentor', models.CharField(max_length=50, verbose_name='Mentor')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='', verbose_name='Certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
