# Generated by Django 6.0.3 on 2026-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='photo',
            field=models.ImageField(default=0, upload_to='', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
