# Generated by Django 6.0.3 on 2026-03-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0002_teammate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='teammate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammate.role', verbose_name='Role'),
        ),
    ]
