# Generated by Django 6.0.3 on 2026-03-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0002_certificate_alter_teammate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammate.teammate', verbose_name='Mentor'),
        ),
    ]
