# Generated by Django 6.0.3 on 2026-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0003_alter_certificate_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
